title: Seamus Tuohy
description: "PGP: 36AC 272E B7CF EDD5 F907 E488 B619 3EC7 3CF0 7AA7"
sourcecode: "https://github.com/elationfoundation/elationfoundation.github.io"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: "http://seamustuohy.com"     # the base hostname & protocol for your site
baseurl: ""                   # the subpath of your site, e.g. /blog

author:
    name:
    facebook:
    scholar:


# if you don't have any of social below, comment the line
# facebook: myfacebook
rss: feed.xml
twitter: seamustuohy
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: seamustuohy
# youtube: myyoutube
# spotify: myspotify
github: elationfoundation
# medium: medium
# vimeo: myvimeo
email: hello@seamustuohy.com


# Build settings
markdown: kramdown
highlighter: rouge



# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments:
    provider:
    disqus:
      short_name:
    livefyre:
      site_id:
    intensedebate:
      account:
    facebook:
      appid:
      num_posts: 5
      width: 580
      colorscheme: light
